[tool.poetry]
name = "perryjones-catan"
version = "0.1.0"
description = ""
authors = ["Perry Jones <perry.jones@softwire.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
